/*
 * Validate the complete run_* configuration.
 *
 * Call once after params have been loaded:
 *
 * validateRunParams(params)
 *
 * Returns true when valid.
 * Calls Nextflow error(...) when invalid.
 *
 * NOTE: THIS IS MONSTLY GENERATED BY CHATGPT ON 1st OCTOBER 2026
 *       HENCE WHY IT IS IN A SEPARATE FILE
 *          - Quite a bit had to be trimmed away as it was
 *            trying to replicate the built in params validation
 *            performed by nf-schema
 *       THIS SOLVES A COMPLICATED ISSUE OF VALIDATING params AGAINST
 *       RUN CONDITIONS REQUIRED PER PROCESS, THIS ISN'T SOMETHING
 *       THAT CAN BE HANDLED VIA THE NEXTFLOW SCHEMA WITHOUT SOME COMPLICATED
 *       JSON CONDITIONALS LOGIC
 *       - Checks params against
 *
 */
def validateRunParams(params) {
    // NOTE: These represent the assembly scopes enabled by each mode.
    def Map RUN_MODES = [
        off       : [] as Set,
        genomic   : ['genomic'] as Set,
        organellar: ['organellar'] as Set,
        both      : ['genomic', 'organellar'] as Set
    ]

    // NOTE: SCHEMA-DEFINED ALLOWED VALUES
    //       These mirror the enum values in nextflow_schema.json.
    //       An annoying requirement, but we can't access these inside the pipeline.
    def Map RUN_ALLOWED_MODES = [
        run_kmers                 : ['genomic', 'off'],
        run_tiara                 : ['genomic', 'organellar', 'both', 'off'],
        run_coverage              : ['genomic', 'organellar', 'both', 'off'],
        run_nt_blast              : ['genomic', 'organellar', 'both', 'off'],
        run_html_report           : ['genomic', 'organellar', 'both', 'off'],
        run_nr_diamond            : ['genomic', 'organellar', 'both', 'off'],
        run_uniprot_diamond       : ['genomic', 'organellar', 'both', 'off'],
        run_kraken                : ['genomic', 'organellar', 'both', 'off'],
        run_fcsgx                 : ['genomic', 'organellar', 'both', 'off'],
        run_fcs_adaptor           : ['genomic', 'organellar', 'both', 'off'],
        run_vecscreen             : ['genomic', 'organellar', 'both', 'off'],
        run_btk_busco             : ['genomic', 'off'],
        run_pacbio_barcodes       : ['genomic', 'organellar', 'both', 'off'],
        run_organellar_blast      : ['genomic', 'off'],
        run_autofilter_assembly   : ['genomic', 'off'],
        run_create_btk_dataset    : ['genomic', 'organellar', 'both', 'off'],
        run_merge_datasets        : ['genomic', 'both', 'off'],
        run_decontaminate_fasta   : ['genomic', 'both', 'off']
    ]

    def List errors = []

    // NOTE: STEP 1. SCOPE-AWARE DEPENDENCY CHECK
    //       Each entry has the form:
    //
    //       child -> parent for these scopes
    //
    //       The dependency is evaluated per assembly scope, rather than comparing
    //       the literal parameter values.
    def Map dependencies = [
        // NOTE: AUTOFILTER requires Tiara and FCS-GX for the same scope.
        run_autofilter_assembly: [
            [parent: 'run_tiara', scopes: ['genomic', 'organellar', 'both'] as Set],
            [parent: 'run_fcsgx', scopes: ['genomic', 'organellar', 'both'] as Set]
        ],

        // NOTE: DECONTAMINATE_FASTA requires AUTOFILTER for genomic scope.
        run_decontaminate_fasta: [
            [parent: 'run_autofilter_assembly', scopes: ['genomic'] as Set]
        ],

        // NOTE: MERGE_BTK_DATASETS requires BTK BUSCO for genomic scope.
        run_merge_datasets: [
            [parent: 'run_btk_busco', scopes: ['genomic'] as Set]
        ]
    ]

    dependencies.each { String childParam, List childDependencies ->
        def String childMode = params[childParam]

        /*
         * Nothing depends on a disabled child.
         */
        if (childMode == 'off') {
            return
        }

        def Set childScopes = RUN_MODES[childMode]

        childDependencies.each { Map dependency ->
            def String parentParam = dependency.parent
            def Set requiredScopes = dependency.scopes
            def String parentMode = params[parentParam]
            def Set parentScopes = RUN_MODES[parentMode]

            //
            // NOTE: Only check scopes where:
            //       - the child actually runs, and
            //       - this particular dependency applies.
            //
            def Set activeScopes = childScopes.intersect(requiredScopes)

            activeScopes.each { String scope ->
                if (!parentScopes.contains(scope)) {
                    errors << (
                        "${childParam}=${childMode} requires " +
                        "${parentParam} to include ${scope} scope; " +
                        "got ${parentParam}=${parentMode}"
                    )
                }
            }
        }
    }

    // NOTE: BTK BUSCO SPECIAL CASE
    //       BTK BUSCO is genomic-only.
    //
    //       In CONDITIONAL mode:
    //
    //       run_btk_busco -> run_autofilter_assembly
    //
    //       for genomic scope.
    //
    //       In MANDATORY mode, BTK may run without autofilter.
    if (
        params.btk_busco_run_mode == 'conditional' &&
        params.run_btk_busco != 'off'
    ) {
        def Set autofilterScopes = RUN_MODES[params.run_autofilter_assembly]

        if (!autofilterScopes.contains('genomic')) {
            errors << (
                "run_btk_busco=${params.run_btk_busco} with " +
                "btk_busco_run_mode=conditional requires " +
                "run_autofilter_assembly to include genomic scope; " +
                "got run_autofilter_assembly=" +
                "${params.run_autofilter_assembly}. " +
                "Use btk_busco_run_mode=mandatory if BTK should run " +
                "without autofilter."
            )
        }
    }

    //
    // NOTE: REPORT ALL ERRORS
    //
    if (errors.isEmpty()) {
        def runParams = params
            .findAll { key, _value -> key.toString().startsWith('run_') }
            .collect { key, value -> " - ${key}=${value}" }
            .join('\n')


        // Organic hand-written here
        // Just so we can use some ANSI color codes in the log output
        // Strip indentation, isn't working here, hence the ugly de-indenting
        log.info(
            """
\u001b[32mRUN_Params are valid:\u001b[39m
${runParams}
            """.stripIndent()
        )
    } else {
        error(
            """
\u001b[31mRUN_Params are invalid:\u001b[39m
${errors.collect { " - ${it}" }.join('\n')}
            """.stripIndent()
        )
    }

    return true
}
