lint:
  actions_awsfulltest: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-ascc_logo_light.png
    - docs/images/nf-core-ascc_logo_light.png
    - docs/images/nf-core-ascc_logo_dark.png
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - conf/igenomes.config
    - lib/nfcore_external_java_deps.jar
    - lib/NfcoreSchema.groovy
    - lib/NfcoreTemplate.groovy
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
  files_unchanged:
    - LICENCE
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - CODE_OF_CONDUCT.md
    - gitignore
    - assets/nf-core-ascc_logo_light.png
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - docs/README.md
    - docs/images/nf-core-ascc_logo_light.png
    - docs/images/nf-core-ascc_logo_dark.png
    - .prettierignore
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - params.show_hidden_params
    - params.schema_ignore_params
    - params.validationSchemaIgnoreParams
  template_strings: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: DLBPointon, eeaunin
  description: Assembly Screen for Cobionts and Contaminants
  force: false
  is_nfcore: false
  name: ascc
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - multiqc
  version: 0.3.0
