repository_type: pipeline
lint:
  files_exist:
    false
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-ascc_logo_light.png
    - docs/images/nf-core-ascc_logo_light.png
    - docs/images/nf-core-ascc_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/branch.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting_comment.yml
    - assets/email_template.html
    - pyproject.toml
    - LICENSE
    - .github/workflows/linting.yml
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
