---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.9
  - conda-forge::biopython=1.78
  - conda-forge::pybedtools=0.9.0
