input: "/nfs/treeoflife-01/teams/tola/users/dp24/ascc/assets/production_testing/samplesheet.csv"
outdir: "OD-TEST-LATEST"
reads_path:
  - /lustre/scratch122/tol/data/d/8/a/6/e/b/Cymbastela_concentrica/genomic_data/odCymConc1/pacbio/fasta/m84047_240125_151157_s4.ccs.bc2031.rmdup.trim.fasta.gz
  - /lustre/scratch122/tol/data/d/8/a/6/e/b/Cymbastela_concentrica/genomic_data/odCymConc1/pacbio/fasta/m84098_240223_150913_s3.ccs.bc2031.rmdup.trim.fasta.gz
reads_type: "hifi"
reads_layout: "SINGLE"
pacbio_barcode_names: "bc2008,bc2009,bc2031"
busco_lineages: "diptera_odb10,insecta_odb10"
sample_id: "Cymbastela_concentrica"
scientific_name: "Cymbastela concentrica"
taxid: 352914
dimensionality_reduction_methods: ["pca", "random_trees"]
# Options are: "pca,umap,t-sne,isomap,lle_standard,lle_hessian,lle_modified,mds,se,random_trees,kernel_pca,pca_svd,autoencoder_sigmoid,autoencoder_linear,autoencoder_selu,autoencoder_relu,nmf"
