input: "/nfs/treeoflife-01/teams/tola/users/dp24/ascc/assets/production_testing/samplesheet.csv"
outdir: "./OUTPUT-results"
reads_path:
  - "/nfs/treeoflife-01/teams/tola/users/dp24/ascc/asccTinyTest_V2/pacbio/Pyoeliiyoelii17XNL_pbtools_simulated_pacbio_reads.fa.gz"
reads_type: "hifi"
reads_layout: "SINGLE"
pacbio_barcode_names: "bc2001,bc2009"
busco_lineages: "diptera_odb10,insecta_odb10"
sample_id: "Pyoeliiyoelii17XNL"
scientific_name: "Plasmodium yoelii yoelii 17XNL"
taxid: 352914
dimensionality_reduction_methods: ["pca", "random_trees"]
# Options are: "pca,umap,t-sne,isomap,lle_standard,lle_hessian,lle_modified,mds,se,random_trees,kernel_pca,pca_svd,autoencoder_sigmoid,autoencoder_linear,autoencoder_selu,autoencoder_relu,nmf"
