name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'sanger-tol/ascc') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.10.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Download test data
        # Download A fungal test data set that is full enough to show some real output.
        run: |
          curl https://tolit.cog.sanger.ac.uk/test-data/resources/ascc/asccTinyTest_V2.tar.gz | tar xzf -

          cp /home/runner/work/ascc/ascc/asccTinyTest_V2/assembly/pyoelii_tiny_testfile_with_adapters.fa /home/runner/work/ascc/ascc/asccTinyTest_V2/assembly/Pyoeliiyoelii17XNL_assembly_hap.fa

      - name: Temporary ASCC Diamond Data
        run: |
          curl https://dp24.cog.sanger.ac.uk/ascc/diamond.dmnd -o diamond.dmnd

      - name: Temporary BLASTN Data
        run: |
          curl https://dp24.cog.sanger.ac.uk/blastn.tar.gz | tar xzf -

      - name: Temporary Accession2TaxID Data
        run: |
          curl https://dp24.cog.sanger.ac.uk/ascc/accession2taxid.tar.gz | tar -xzf -

      - name: Download the NCBI taxdump database
        run: |
          mkdir ncbi_taxdump
          curl -L https://ftp.ncbi.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz | tar -C ncbi_taxdump -xzf -

      - name: Download the FCS-gx database
        run: |
          mkdir FCS_gx
          wget -cq https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/test-only/test-only.taxa.tsv -O FCS_gx/all.taxa.tsv
          wget -cq https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/test-only/test-only.gxi -O FCS_gx/all.gxi
          wget -cq https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/test-only/test-only.gxs -O FCS_gx/all.gxs
          wget -cq https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/test-only/test-only.meta.jsonl -O FCS_gx/all.meta.jsonl
          wget -cq https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/FCS/database/test-only/test-only.blast_div.tsv.gz -O FCS_gx/all.blast_div.tsv.gz

      - name: Download the BUSCO lineage database
        run: |
          mkdir busco_database
          curl -L https://tolit.cog.sanger.ac.uk/test-data/resources/busco/blobtoolkit.GCA_922984935.2.2023-08-03.lineages.tar.gz | tar -C busco_database -xzf -

      - name: Download the kraken2 database
        run: |
          mkdir kraken2
          curl -L https://raw.githubusercontent.com/nf-core/test-datasets/modules/data/genomics/sarscov2/genome/db/kraken2.tar.gz | tar -C kraken2 -xzf -

      - name: Download the subset of NT database
        run: |
          mkdir NT_database
          curl -L https://ftp.ncbi.nlm.nih.gov/blast/db/18S_fungal_sequences.tar.gz | tar -C NT_database -xzf -

      - name: Download the subset of Diamond database
        run: |
          mkdir diamond
          wget -c https://tolit.cog.sanger.ac.uk/test-data/resources/diamond/UP000000212_1234679_tax.dmnd -O diamond/UP000000212_1234679_tax.dmnd

      - name: Download the vecscreen test data
        run: |
          mkdir vecscreen
          curl -L https://ftp.ncbi.nlm.nih.gov/blast/db/v4/16SMicrobial_v4.tar.gz | tar -C vecscreen -xzf -

      - name: Run FULL pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} \
            -profile test,docker \
            -params-file ${GITHUB_WORKSPACE}/assets/github_testing/github_test.yaml \
            --input ${GITHUB_WORKSPACE}/assets/github_testing/samplesheet.csv \
            --exclude btk_busco \
            --organellar_exclude btk_busco

      - name: Upload Nextflow log
        uses: actions/upload-artifact@v4
        with:
          name: nextflow-${{ strategy.job-index }}-log
          path: /home/runner/work/ascc/ascc/.nextflow.log
          if-no-files-found: warn
          include-hidden-files: true
          retention-days: 1

      - uses: actions/download-artifact@v4
        with:
          pattern: nextflow-*
          merge-multiple: true
